name: multi stage

on:
  workflow_dispatch:

jobs:
  stage_1:
    name: stage 1
    runs-on: ubuntu-latest
    outputs:
      tag_from_env: ${{env.image_tag}}
      tag_from_output: ${{steps.create_output.outputs.tag_from_output}}
    steps:
      - name: checkout
        # https://github.com/actions/checkout
        uses: actions/checkout@v3
        with:
          # checkout complete history
          fetch-depth: 0
      - name: git state
        run: git status
      - name: echo something
        run: echo hello repo
      - name: pass env values
        run: echo "image_tag=latest" >> $GITHUB_ENV
      - name: create output
        id: create_output
        run: echo "::set-output name=tag_from_output::latest-from-output"
      - name: use env in same stage
        run: echo image_tag=${{env.image_tag}}

  stage_2:
    name: stage 2
    needs: stage_1
    runs-on: ubuntu-latest
    outputs:
      tag_from_stage_1: ${{steps.create_output.outputs.tag_from_stage_1}}
      tag_from_stage_2: ${{steps.create_output.outputs.tag_from_stage_2}}
    steps:
      - name: use env from stage_1
        run: echo image_tag=${{needs.stage_1.env.image_tag}}
      - name: use output from stage_1
        run: |
          echo tag_from_env=${{needs.stage_1.outputs.tag_from_env}}
          echo tag_from_output=${{needs.stage_1.outputs.tag_from_output}}
      - name: pass outputs
        id: create_output
        run: |
          echo "::set-output name=tag_from_stage_1::${{needs.stage_1.outputs.tag_from_env}}"
          echo "::set-output name=tag_from_stage_2::stage_2-tag"
  stage_3:
    name: stage 3
    runs-on: ubuntu-latest
    steps:
      - name: list location
        run: ls -lha

  stage_4:
    name: stage 4
    needs: stage_3
    runs-on: ubuntu-latest
    outputs:
      tag_from_stage_4: ${{steps.create_output.outputs.tag_from_stage_4}}
    steps:
      - name: list env
        run: env
      - name: create output tag
        id: create_output
        run: echo "::set-output name=tag_from_stage_4::stage_4-tag"

  stage_5:
   name: stage 5
   needs: [stage_2, stage_4]
   runs-on: ubuntu-latest
   outputs:
     next_stage: ${{steps.set_next_stage.outputs.next_stage}}
   steps:
    - name: show tags from other stages
      run: |
        echo tag_from_stage_1=${{needs.stage_2.outputs.tag_from_stage_1}}
        echo tag_from_stage_2=${{needs.stage_2.outputs.tag_from_stage_2}}
        echo tag_from_stage_4=${{needs.stage_4.outputs.tag_from_stage_4}}
    - name: set next stage
      uses: satackey/action-js-inline@v0.0.2
      id: set_next_stage
      with:
        script: |
          const core = require('@actions/core')
          const rand = Math.round(Math.random() * 100)
          console.log("rand...", rand)
          core.setOutput('next_stage', rand > 50 ? 6 : 7)
    - name: echo next stage
      run: echo next_stage=${{steps.set_next_stage.outputs.next_stage}}

  stage_6:
    # https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#jobsjob_idif
    if: needs.stage_5.outputs.next_stage == 6
    name: stage 6
    needs: stage_5
    runs-on: ubuntu-latest
    steps:
      - name: show received next step
        run: echo next_stage=${{needs.stage_5.outputs.next_stage}}

  stage_7:
    # https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#jobsjob_idif
    if: needs.stage_5.outputs.next_stage == 7
    name: stage 7
    needs: stage_5
    runs-on: ubuntu-latest
    steps:
      - name: show received next step
        run: echo next_stage=${{needs.stage_5.outputs.next_stage}}

  stage_8:
    name: stage 8
    needs: stage_6
    runs-on: ubuntu-latest
    steps:
     - name: say something
       run: echo stage 6 runned before me

  stage_9:
    name: stage 9
    needs: stage_7
    runs-on: ubuntu-latest
    steps:
     - name: say something
       run: echo stage 7 runned before me