name: multi stage

on:
  workflow_dispatch:

jobs:
  stage-1:
    name: stage 1 job
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        # https://github.com/actions/checkout
        uses: actions/checkout@v3
        with:
          # checkout complete history
          fetch-depth: 0
      - name: git state
        run: git status
      - name: echo something
        run: echo hello repo
      - name: pass env values
        run: echo "image_tag=latest" >> $GITHUB_ENV

  stage-2:
    name: stage 2 job
    needs: stage-1
    runs-on: ubuntu-latest
    steps:
      - name: stage2.step1
        run: echo image_tag=${{env.image_tag}}
