name: multi stage

on:
  workflow_dispatch:

jobs:
  stage_1:
    name: stage 1 job
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        # https://github.com/actions/checkout
        uses: actions/checkout@v3
        with:
          # checkout complete history
          fetch-depth: 0
      - name: git state
        run: git status
      - name: echo something
        run: echo hello repo
      - name: pass env values
        run: echo "image_tag=latest" >> $GITHUB_ENV

  stage_2:
    name: stage 2 job
    needs: stage_1
    runs-on: ubuntu-latest
    steps:
      - name: stage2.step1 can access env from state_1
        run: echo image_tag=${{needs.stage_1.env.image_tag}}
      - name: is the repo from stage_1 still here?
        run: git status
